
spring:
  application:
    name: stream
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:6666/stream?currentSchema=uvideos
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 1
      connection-timeout: 30000
      pool-name: SpringBootPgBouncerHikariCP
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
#logging:
#  level:
#    org:
#      hibernate: DEBUG


minio:
  service: users
  endpoint: http://localhost:8000
  accessKey: 32t2cwCIdputIRatOn8I
  secretKey: nsSM4jKBFPWDbqFrdBrLcFOoMitQvQOvfCDFTILB
server:
  port: 1021
